name: Deploy to heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x']
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@main
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          cd client-app
          npm install
          npm run build
      # - name: Commits before Deployment
      #   run: git config user.email "mohamedmouiguina7@gmail.com" && git config user.name "MOUIGUINA MOHAMED" && git add -A && git commit -m "Updated code"
      - name: update branch
        run: |
           docker login --username=osaelh --password=$HEROKU_API_KEY registry.heroku.com
           heroku container:login
           heroku git:remote -a reach4thesky
           git config --global user.email "oussamaelh@gmail.com" && git config --global user.name "osa elh" && git add . && git commit -m 'update repo'
           git fetch --all --unshallow
           git push heroku main 
      - name: Deploy to heroku  
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "reach4thesky" #Must be unique in Heroku
          heroku_email: "oussamaelh@gmail.com"

